language: python
python:
  - "3.5" #versão do python
env: #Configuração das variáveis de ambiente
  - SECRET_KEY=TopSecretKey DEBUG=True ALLOWED_HOSTS=127.0.0.1 EMAIL_BACKEND=django.core.mail.backends.console.EmailBackend
install:
  - pip install -r requirements.txt
script: #comandos a serem executados para realizar o teste
  - python manage.py check
  - python manage.py test